[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/**/*.prisma"]

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "public"
  autoLaunch = true 